remote_theme: WildCodeSchool/workshops-jekyll-theme

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # possible values: default or tic-tac

title: "Terminal"
show_clone: false
